services:
  - type: web
    name: django-blog
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString

databases:
  - name: blog-db
